/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.79
 * Generated at: 2023-01-08 04:54:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.khachhang;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import model.KhachHangModel;

public final class information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.KhachHangModel");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\"\r\n");
      out.write("	content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<title>Đăng ký tài khoản</title>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"\r\n");
      out.write("	integrity=\"sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js\"\r\n");
      out.write("	integrity=\"sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".red {\r\n");
      out.write("	color: red;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

	KhachHangModel kh = (KhachHangModel) session.getAttribute("khachHang");
	if (kh == null) {
	
      out.write("\r\n");
      out.write("	<h1>Vui lòng đăng nhập!</h1>\r\n");
      out.write("	");

	} else {
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	");

	String baoLoi = request.getAttribute("baoLoi") + "";
	baoLoi = baoLoi.equals("null") ? "" : baoLoi;

	String hoTen = kh.getHoTen();
	boolean gioiTinhT = kh.isGioiTinh();
	String gioiTinh = "";
	if (gioiTinhT) {
		gioiTinh = "Nam";
	} else {
		gioiTinh = "Nữ";
	}
	String ngaySinh = kh.getNgaySinh().toString();
	String diaChiKhachHang = kh.getDiaChi();
	String diaChiMuaHang = kh.getDiaChiMuaHang();
	String diaChiNhanHang = kh.getDiaChiNhanHang();
	String soDienThoai = kh.getSoDienThoai();
	String email = kh.getEmail();
	boolean dongYNhanMail = kh.isDangKyNhanTin();
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\">\r\n");
      out.write("		<div class=\"text-center\">\r\n");
      out.write("			<h1>Thay Đổi Thông Tin</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"red\">\r\n");
      out.write("			");
      out.print(baoLoi);
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"red\" id=\"baoLoi\"></div>\r\n");
      out.write("		");
 String url = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
		+ request.getContextPath(); 
      out.write("\r\n");
      out.write("		<form class=\"form\" action=\"");
      out.print(url );
      out.write("/khach-hang\" method=\"post\">\r\n");
      out.write("			<input type=\"hidden\" name=\"action\" value=\"thay-doi-tt\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("\r\n");
      out.write("					<h3>Thông tin khách hàng</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"hoVaTen\" class=\"form-label\">Họ và tên</label> <input\r\n");
      out.write("							type=\"text\" class=\"form-control\" id=\"hoVaTen\" name=\"hoVaTen\"\r\n");
      out.write("							value=\"");
      out.print(hoTen);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"gioiTinh\" class=\"form-label\">Giới tính</label> <select\r\n");
      out.write("							class=\"form-control\" id=\"gioiTinh\" name=\"gioiTinh\">\r\n");
      out.write("							<option></option>\r\n");
      out.write("							<option value=\"Nam\"\r\n");
      out.write("								");
      out.print(gioiTinh.equals("Nam") ? "selected='selected'" : "");
      out.write(">Nam</option>\r\n");
      out.write("							<option value=\"Nữ\"\r\n");
      out.write("								");
      out.print(gioiTinh.equals("Nữ") ? "selected='selected'" : "");
      out.write(">Nữ</option>\r\n");
      out.write("							<option value=\"Khác\"\r\n");
      out.write("								");
      out.print(gioiTinh.equals("Khác") ? "selected='selected'" : "");
      out.write(">Other</option>\r\n");
      out.write("						</select>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"ngaySinh\" class=\"form-label\">Ngày sinh</label> <input\r\n");
      out.write("							type=\"date\" class=\"form-control\" id=\"ngaySinh\" name=\"ngaySinh\"\r\n");
      out.write("							value=\"");
      out.print(ngaySinh);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-sm-6\">\r\n");
      out.write("					<h3>Địa chỉ</h3>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiKhachHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							khách hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiKhachHang\" name=\"diaChiKhachHang\"\r\n");
      out.write("							value=\"");
      out.print(diaChiKhachHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiMuaHang\" class=\"form-label\">Địa chỉ mua\r\n");
      out.write("							hàng</label> <input type=\"text\" class=\"form-control\" id=\"diaChiMuaHang\"\r\n");
      out.write("							name=\"diaChiMuaHang\" value=\"");
      out.print(diaChiMuaHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"diaChiNhanHang\" class=\"form-label\">Địa chỉ\r\n");
      out.write("							nhận hàng</label> <input type=\"text\" class=\"form-control\"\r\n");
      out.write("							id=\"diaChiNhanHang\" name=\"diaChiNhanHang\"\r\n");
      out.write("							value=\"");
      out.print(diaChiNhanHang);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dienThoai\" class=\"form-label\">Điện thoại</label> <input\r\n");
      out.write("							type=\"tel\" class=\"form-control\" id=\"dienThoai\" name=\"dienThoai\"\r\n");
      out.write("							value=\"");
      out.print(soDienThoai);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"email\" class=\"form-label\">Email</label> <input\r\n");
      out.write("							type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("							value=\"");
      out.print(email);
      out.write("\">\r\n");
      out.write("					</div>\r\n");
      out.write("					<hr />\r\n");
      out.write("\r\n");
      out.write("					<div class=\"mb-3\">\r\n");
      out.write("						<label for=\"dongYNhanMail\" class=\"form-label\">Đồng ý nhận\r\n");
      out.write("							email</label> <input type=\"checkbox\" class=\"form-check-input\"\r\n");
      out.write("							value=\"dongYNhanMail\" id=\"dongYNhanMail\" name=\"dongYNhanMail\"\r\n");
      out.write("							");
      out.print(dongYNhanMail ? "checked" : "");
      out.write(">\r\n");
      out.write("					</div>\r\n");
      out.write("					<input class=\"btn btn-primary form-control\" type=\"submit\"\r\n");
      out.write("						value=\"Đăng ký\" name=\"submit\" id=\"submit\" />\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	");

	}
	
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	function kiemTraMatKhau() {\r\n");
      out.write("		var matKhau = document.getElementById(\"matKhau\").value;\r\n");
      out.write("		var matKhauC = document.getElementById(\"matKhauNhapLai\").value;\r\n");
      out.write("		if (matKhau != matKhauC) {\r\n");
      out.write("			document.getElementById(\"msg\").innerHTML = \"Mật khẩu xác nhận chưa đúng\";\r\n");
      out.write("			return false;\r\n");
      out.write("		} else {\r\n");
      out.write("			document.getElementById(\"msg\").innerHTML = \"\";\r\n");
      out.write("			return true;\r\n");
      out.write("		}\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
